// src/App.svelte
<script>
    import Hero from "./lib/Hero.svelte";
    import WeatherChart from "./lib/WeatherChart.svelte";
    import DateSwitcher from "./lib/DateSwitcher.svelte";

    import { DateStore } from "./stores/DateStore";
</script>

<main
    class="text-fg max-w-5xl mx-auto justify-start items-center flex flex-col gap-10 py-16"
>
    <Hero />
    <DateSwitcher />

    <WeatherChart
        day={parseInt($DateStore.slice(8, 10))}
        month={parseInt($DateStore.slice(5, 7))}
        year={parseInt($DateStore.slice(0, 4))}
    />
</main>

// src/App.jsx
import "./index.css";
import WeatherChart from "./components/WeatherChart";

function App() {
    return (
        <div className="text-fg max-w-5xl mx-auto justify-start items-center flex flex-col gap-10 py-16">
            <div className="font-mono lg:text-5xl md:text-4xl text-3xl transition-all duration-300">
                Weather Data Collector <span className="underline">Baku</span>
            </div>
            <WeatherChart day={4} month={8} year={2022}/>
        </div>
    );
}

export default App;
